export const products = [
  {
    id: "p1",
    title: `Adidas Ultra Boost`,
    price: 120.99,
    priceSale: "",
    status: "",
    colors: ["#000000", "#FFFFFF", "#FF0000"],
    productImage: `https://example.com/product_1.jpg`,
  },
  {
    id: "p2",
    title: `Adidas NMD R1`,
    price: 99.99,
    priceSale: "",
    status: "new",
    colors: ["#0000FF", "#FFFFFF", "#00FF00"],
    productImage: `https://example.com/product_2.jpg`,
  },
  {
    id: "p3",
    title: `Adidas Superstar`,
    price: 80.50,
    priceSale: 60.25,
    status: "sale",
    colors: ["#FFFFFF", "#000000", "#FFA500"],
    productImage: `https://example.com/product_3.jpg`,
  },
  {
    id: "p4",
    title: `Adidas Stan Smith`,
    price: 85.75,
    priceSale: "",
    status: "",
    colors: ["#FFFFFF", "#000000", "#808080"],
    productImage: `https://example.com/product_4.jpg`,
  },
  {
    id: "p5",
    title: `Adidas Yeezy Boost 350 V2`,
    price: 220.00,
    priceSale: "",
    status: "new",
    colors: ["#000000", "#FFFFFF", "#FFA500"],
    productImage: `https://example.com/product_5.jpg`,
  },
  {
    id: "p6",
    title: `Adidas Gazelle`,
    price: 79.99,
    priceSale: "",
    status: "",
    colors: ["#008000", "#000000", "#FFFFFF"],
    productImage: `https://example.com/product_6.jpg`,
  },
  {
    id: "p7",
    title: `Adidas Deerupt Runner`,
    price: 89.99,
    priceSale: "",
    status: "new",
    colors: ["#000000", "#FFFFFF", "#FF0000"],
    productImage: `https://example.com/product_7.jpg`,
  },
  {
    id: "p8",
    title: `Adidas Continental 80`,
    price: 75.00,
    priceSale: 60.00,
    status: "sale",
    colors: ["#FFFFFF", "#000000", "#FFA500"],
    productImage: `https://example.com/product_8.jpg`,
  },
  {
    id: "p9",
    title: `Adidas Samba`,
    price: 70.00,
    priceSale: "",
    status: "",
    colors: ["#000000", "#FFFFFF", "#FFD700"],
    productImage: `https://example.com/product_9.jpg`,
  },
  {
    id: "p10",
    title: `Adidas EQT Support ADV`,
    price: 110.00,
    priceSale: "",
    status: "",
    colors: ["#FFFFFF", "#000000", "#00FF00"],
    productImage: `https://example.com/product_10.jpg`,
  },
];
